<h2>[[+name]]</h2>
<table>
  <thead>
    <tr>
        <th>Name</th>
        <th>Dimensions</th>
        <th>Requirements</th>
        <th>Price</th>
    </tr>
  </thead>
  <tbody>
    [[+products]]
  </tbody>
</table>